chalkak2023/Chalkak-Frontend

src/modals/LoginModal.js
src/modals/SignupModal.js

- modal state의 show값이 true일 때 modalName을 각각 login, signup이면 보이도록 모달창을 만듬
- 이메일 인증 토큰을 쿼리로 넘겨주는게 아니라 바디로 넘겨주도록 만듬
- 폴더 구조를 바꿔야하거나 파일 이름을 바꿔줘야하는 경우에 코멘트를 달면 반영할 예정.

LoginModal, SignupModal 작성(SampleModal 조금 변형)

---

src/routes/meetups/MeetupsCreateModal.js
src/routes/meetups/MeetupsDetailModal.js
src/routes/meetups/MeetupsList.js
src/store/meetup.slice.js

- 로그인된 유저 정보를 사용해 Meetups API와 연동 완료 (추가, 삭제, 모임 참여, 취소 기능)

feat: meetup 백엔드 API와 연동 (추가, 삭제, 모임 참여, 취소)

---

src/routes/auth/AuthSigninModal.js

- resolve #14 
- 로그인 API 요청 후 status code를 200으로 검증
https://github.com/chalkak2023/Chalkak-Backend/pull/74 가 merge되면 같이 머지되어야함.

refactor: 백엔드의 로그인 스테이터스 코드를 200으로 변경하여 클라이언트 측에서도 변경

---

src/App.js
src/routes/collections/CollectionsList.js
src/routes/components/NavSideBar.js
src/store/collection.slice.js
src/store/store.js

- resolve #20 - 무한스크롤/검색/로딩 기능 포함
정상 작동

feat: 콜렉션 조회 페이지 구현

---

src/App.js
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotCreateModal.js
src/routes/Photospot/PhotospotView.js
src/routes/auth/AuthSigninModal.js
src/routes/collections/CollectionsList.js
src/routes/hoc/auth.js
src/routes/oauth/KakaoLoginRedirect.js
src/routes/oauth/NaverLoginRedirect.js
src/store/user.slice.js

- 콜렉션 리스트에서 해당 photospot으로 이동 추가
- 로그인 인증 필요한 페이지 로그인 체크
기능이 정상적으로 동작
- https://github.com/chalkak2023/Chalkak-Backend/pull/96

feat: 콜렉션 리스트에서 해당 photospot으로 이동 추가

---

src/routes/Photospot/Photospot.css
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotCreateModal.js
src/routes/Photospot/PhotospotDetailModal.js
src/routes/Photospot/PhotospotModifyModal.js
src/routes/Photospot/PhotospotView.js

- 포토스팟 이미지 여러장 업로드
- 포토스팟 이미지 수정, 삭제
- https://github.com/chalkak2023/Chalkak-Backend/pull/112

feat: 이미지 여러장 업로드, 수정, 삭제 추가

---

src/App.js
src/routes/Photospot/Photospot.css
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotCreateModal.js
src/routes/Photospot/PhotospotDetailModal.js
src/routes/Photospot/PhotospotModifyModal.js
src/routes/Photospot/PhotospotView.js

- resolve #58 
- 지도 확대 축소 기능 추가, CSS변경, URI 변경
-

feat: 포토스팟 중간 발표 전 QA - 1차

---

src/routes/meetups/MeetupsCreateModal.js
src/routes/meetups/MeetupsDetailModal.js
src/routes/meetups/MeetupsList.css
src/routes/meetups/MeetupsList.js

- resolve #56 
- api 요청 시 실패한 응답 값에 대한 처리 기능 추가
- 기능 사용에 불편함을 유발하는 ui 수정 - 모임 목록의 내용 2줄 이상 시 생략되게 변경
- 모임 참여 누르는 순간 이미 모집 마감인 경우 알림이 뜨고 갱신되어 모집 마감인 걸 알 수 있게 변경
- 정원이 다 찬 경우 모집 마감으로 뜨게 변경
- https://github.com/chalkak2023/Chalkak-Backend/pull/126 적용되야 확인 가능

refactor: 모임: 중간발표 전 QA - 1차

---

src/environments/admin.js
src/routes/admin/AdminAccount.js
src/routes/admin/AdminCollection.js
src/routes/admin/AdminFAQ.js
src/routes/admin/AdminMeetup.js
src/routes/admin/AdminPhotospot.js
src/routes/admin/AdminTable.js
src/routes/admin/AdminUser.js
src/routes/admin/components/AdminAccountDeleteButton.js
src/routes/admin/components/AdminCollectionDeleteButton.js
src/routes/admin/components/AdminMeetupDeleteButton.js
src/routes/admin/components/AdminPhotospotDeleteButton.js
src/routes/admin/components/AdminUserBlockButton.js
src/routes/admin/modals/AdminCreateAccountModal.js
src/routes/admin/modals/AdminCreateFAQModal.js
src/routes/admin/modals/AdminPutFAQModal.js
src/routes/admin/modals/AdminSigninModal.js
src/utils/handleDate.js

- #60 
- 맞춤법, 오타 수정
- moment-timezone 사용 삭제
- 직관적이지 않은 함수 이름을 수정
- data?.length를 사용하지 않고 Array.isArray(data)로 배열인지를 확인. (lodash 안 쓴 이유는 이게 원래 의도에 맞아서)

refactor: 관리자 중간발표 전 QA - 1차 누락 반영

---

src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotView.js
src/routes/collections/CollectionModifyModal.js
src/routes/collections/CollectionsCreateModal.js
src/routes/collections/CollectionsList.js

- resolve #63 
- 콜렉션 목록 내 #키워드 조회 기능 추가
- 콜렉션 포토스팟 페이지 이동 시 URL 내 collectionId 추가

feat: 콜렉션 중간발표 전 QA - 1차

---

src/routes/auth/AuthSigninModal.js
src/routes/auth/AuthSignupModal.js
src/routes/auth/ChangePasswordModal.js

- resolve #67 
- 메일 발송, 인증번호 확인 후에 버튼 눌려있도록 하기
- 메일 발송단계에 따라 텍스트 변경
- 비밀번호 조건 텍스트로 써놓기
- 로그인 모달에서 비밀번호 치고 엔터 치면 로그인 시도
- 회원가입, 비밀번호변경 요청 성공시에 이메일 인증상태 초기화

feat: 인증 중간발표 전 QA - 2차

---

src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotModifyModal.js
src/routes/Photospot/PhotospotView.js
src/routes/components/NavSideBar.js

- resolve #77 
- 마지막 사진을 지우면 버그가 발생하던 부분 css 문제였고 이미지 index를 인식해서 마지막 이미지가 삭제되면 첫번째 사진이 보여주게 수정
- photospotModify에서 +이모지를 클릭하고 이미지를 추가하는 부분을 보여주던 부분 삭제 후 항상 보여주도록 수정
- deletePhoto에서 이미지를 하나하나 삭제 요청을 보내는 기능에서 삭제한 이미지를 하나하나 배열에 모아두고 수정 버튼을 눌러야지 삭제가 되도록 수정
- https://github.com/chalkak2023/Chalkak-Backend/pull/134

chore: 포토스팟 중간발표 전 QA - 2차

---

src/App.js
src/routes/NotFound.js

- resolve #70 
- 아무런 route path와도 일치하지 않을 때 NotFound 컴포넌트가 보이도록 설정

feat: 페이지를 찾을 수 없을 때의 404 페이지 추가

---

src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotView.js
src/routes/meetups/MeetupsList.js

- resolve #67 
- 포토스팟 페이지 내 콜렉션명만 나타나도록 '콜렉션' 삭제
- 모임 목록에서 나의 모임 선택 상태로 모임 삭제 시 제대로 삭제 안되는 부분 수정
- 나의 모임 체크 상태에서 삭제 시 체크 해제되며 resetMeetups() 함수 실행되게 변경

chore: 콜렉션 중간발표 전 QA - 2차 

---

src/routes/Main.js
src/routes/main/MainCarousel.js
src/routes/main/MainCollections.js
src/routes/main/MainMeetups.js

- 임시 메인 페이지 추가
- 각 콜렉션, 모임 최근 3개 데이터만 보여주게 설정

feat: 임시 메인 페이지 추가

---

src/App.css
src/App.js
src/routes/Photospot/Photospot.css
src/routes/collections/CollectionsList.js
src/routes/components/Header.js
src/routes/main/MainCarousel.js
src/routes/main/MainCollections.js
src/routes/main/MainMeetups.js
src/routes/meetups/MeetupsList.js

feat:사이트 공통 css 추가

---

src/routes/Photospot/Photospot.css
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotCreateModal.js
src/routes/Photospot/PhotospotDetailModal.js
src/routes/Photospot/PhotospotModifyModal.js
src/routes/Photospot/PhotospotView.js
src/routes/collections/CollectionModifyModal.js

- resolve #88 
- collectionModify 버튼 스타일 변경 (중앙 정렬, 색상 변경)
- photospot 장소 검색 스타일 변경 (콜렉션과 모임 검색창과 스타일 통일)
- photospot 나의 위치 스타일 변경 (상단에서 좌측 하단 지도 축소 확대 옆으로)
- photospotCreate 버튼 스타일 변경 (중앙 정렬)
- photospotModify 버튼 스타일 변경 (중앙 정렬, 색상 변경)
- photospotDetail 스타일 변경 (타이틀 굵기 변경, 설명 부분 변경)

chore: 포토스팟 스타일 변경

---

src/App.css
src/pages/UserPage.js
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotView.js
src/routes/components/Hamburger_icon.svg
src/routes/components/Header.css
src/routes/components/Header.js
src/routes/components/NavSideBar.js
src/store/footer.slice.js
src/store/store.js

- resolve #94 
- nav 버튼 header로 옮김
- header sticky 적용
- 지도 나오는 photospot, photospot-view 컴포넌트에서는 footer 안나오게 수정
- nav 메뉴 글자 변경하며 같이 변경된 meetups 오타 수정

#refactor: header, footer 수정

---

src/routes/Photospot/PhotospotView.js

photospot-view map 높이 변경

---

src/routes/Photospot/Photospot.js

- photospot 컴포넌트 진입 시 Toast를 통해 생성 팁 노출

fix: 콜렉션 -> 포토스팟 수정 컴포넌트 진입 시 포토스팟 생성 팁 alert

---

src/routes/collections/Collection.css
src/routes/collections/CollectionModifyModal.js
src/routes/collections/CollectionsCreateModal.js

- 맥에서 collection tag에 대한 등록, 수정 동작이 제대로 안되던 문제에 대해 아예 로직을 바꿔 문제 해결
- 윈도우에서도 잘 동작하는지 테스트 부탁드립니다.

fix: 맥에서 collection tag 등록이 제대로 안되던 문제 수정

---

src/routes/Photospot/PhotospotCreateModal.js
src/routes/Photospot/PhotospotModifyModal.js

- 포토스팟 생성, 수정 제목, 내용 글자 수 제한 추가

hot-fix: 포토스팟 제목, 내용 글자 제한 추가

---

src/routes/collections/Collection.css
src/routes/collections/CollectionModifyModal.js
src/routes/collections/CollectionsCreateModal.js
src/routes/collections/CollectionsList.js
src/routes/main/Main.css
src/routes/main/MainCollections.js

- resolve #104 
- 제목: 20자 이하, 필수 1개 이상 입력
- 내용: 60자 이하, 필수 1개 이상 입력
- 키워드: 8글자 이하, 1~6개까지 등록

hot-fix: 콜렉션 제목/내용/키워드 글자수 제한 추가

---

src/routes/auth/AuthSigninModal.js
src/routes/auth/AuthSignupModal.js

- 회원가입 후 바로 로그인 가능하도록 기능 추가
- 회원가입 시에 닉네임 필수 입력 조건과 16글자 이내 조건 추가
- 회원가입, 로그인 시 버튼 비활성화 상태 조건 리팩토링
- 비밀번호 변경 관련은 백엔드도 건드려야해서 추후 수정 예정

hot-fix: 회원가입과 로그인 관련 수정

---

src/routes/main/Main.css
src/routes/main/MainCarousel.js

fix: 메인페이지 케러셀 흰색 배경 오작동 수정

---

src/routes/components/Footer.js

- footer 관리자페이지 -> 서비스 이용안내로 변경

chore: footer - 관리자페이지 -> 서비스 이용안내로 변경

---

.env.development
.env.production
src/App.js
src/pages/AdminPage.js
src/routes/admin/AdminSignin.js
src/routes/admin/modals/AdminSigninModal.js
src/routes/auth/AuthSigninModal.js
src/routes/auth/AuthSignupModal.js
src/routes/auth/ResetPassword.js
src/routes/auth/ResetPasswordModal.js
src/routes/components/AdminHeader.js
src/routes/components/Header.js
src/utils/api-axios.js

- resolve #112
- 회원가입 창에서 엔터를 누르면 회원가입 시도
- 로그인 시 메인페이지로 이동
- 이메일 인증 관련해서는 토큰 재발급 요청 x
- resolve #113
- 관리자 로그인을 안 하면 관리자 페이지를 못 봄
- 비밀번호 재설정 기능 (로그인 창안에 버튼을 만듬)
- 비밀번호 재설정 기능의 경우에는 백엔드의 pr과 함께 테스트해야함.
- https://github.com/chalkak2023/Chalkak-Backend/pull/148

refactor: 인증 유저 설문조사 피드백 반영 (+관리자페이지 로그인 필수, 비밀번호 재설정)

---

src/routes/Photospot/Photospot.css
src/routes/Photospot/Photospot.js
src/routes/Photospot/PhotospotDetailModal.js
src/routes/Photospot/PhotospotModifyModal.js
src/routes/Photospot/PhotospotView.js
src/routes/main/MainCarousel.js

- resolve #115 
- 포토스팟 수정 시 변경된 내용 없으면 알림 보여주고 모달 끄기 추가
- 포토스팟 모달 안끄고 뒤로가기 누르면 생기는 버그 수정
- 포토스팟 이미지 삭제 버튼 변경
- 메인페이지 슬라이드 콜렉션 연결 추가
- 카카오지도 첫번째 배열 좌표로 정렬하는 방식으로 수정
- https://github.com/chalkak2023/Chalkak-Backend/pull/150

feat: 포토스팟 변경된 내용 없으면 예외처리 추가

---

.github/workflows/s3.deploy.yml
package.json

- resolve #121 
- dev 브랜치에 pr을 merge하거나 커밋을 push하면 트리거되는 배포 자동화 워크플로우 적용. 
- s3에 파일을 업로드하고 cloudfront가 사용자에게 서비스.
- merge가 되면 cloudfront의 접속 주소를 www.chalkak.site로 바꿀 예정(현재는 test.chalkak.site)
- dev가 업데이트될 때 캐시를 수동으로 현재는 지워줘야하는데, 업데이트되면 cloudfront의 캐시가 바뀔 방법은 찾고 있음.

feat: s3와 cloudfront를 사용한 배포 자동화

---

package-lock.json
package.json
src/routes/Main.js
src/routes/meetups/MeetupsList.css
src/routes/meetups/MeetupsList.js

- resolve #117 
- https://github.com/chalkak2023/Chalkak-Backend/pull/159
- 모임 전체 목록에서 내가 만든 모임, 참여한 모임, 참여 다 찬 모임에 대한 구분 가능하게 변경
- 나의 모임 -> 내가 만든 모임으로 변경 및 백엔드에서 데이터 불러와서 처리되게 변경
- 내가 참여한 모임 기능 추가
- 추가된 기능 모두 페이지네이션 및 검색 기능 사용 가능
- lodash 추가

feat: meetups - 내가 참여한 모임, 내가 만든 모임에 대한 api 추가

---

.github/workflows/s3.deploy.yml

- pr과 push를 둘 다 이벤트 설정해놨더니 pr 머지시에 두번 실행되는 걸 push를 빼버려서 1번만 실행되도록 수정

fix: pr 머지시 배포가 두번 실행되는 문제 해결

---

src/routes/Photospot/PhotospotCreateModal.js

- 포토스팟 생성 모달 textarea 높이 수정, placeholder 수정

chore: textarea 높이 수정, placeholder 수정

---

src/routes/chat/Chat.css
src/routes/chat/Chat.js
src/routes/components/Header.js
src/routes/components/NavSideBar.js
src/routes/meetups/MeetupsDetailModal.js
src/routes/meetups/MeetupsList.js

- 모임 참여 멤버 목록 기능 추가
- 채팅방 멤버 목록 기능 추가

Feat: 모임 / 채팅 참여중인 멤버 목록 기능 추가

---

src/routes/chat/Chat.js
src/routes/meetups/MeetupsCreateModal.js
src/routes/meetups/MeetupsList.js

- https://github.com/chalkak2023/Chalkak-Backend/pull/170
- 모임 장소명 글자 제한 8 글자 -> 20 글자로 변경
- 클릭한 모임이 이미 삭제된 경우에 대한 예외처리 추가
- 로그인 안된 상태로 /chat 접근 못하게 변경

refactor: meetups, chat 피드백 반영사항 적용
